// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WealthVaultApi.Data;

#nullable disable

namespace WealthVaultApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202021534_AddedLiabilitiesAndObligationsModels")]
    partial class AddedLiabilitiesAndObligationsModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WealthVaultApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostBasis")
                        .HasColumnType("numeric");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<int>("IncomeFrequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastIncomeDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("NextIncomeDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PurchasePricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("SecondaryCurrency")
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<decimal?>("YieldPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("WealthVaultApi.Models.AssetTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DefaultYield")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiability")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxAdvantaged")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("WealthVaultApi.Models.Liabilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Creditor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecured")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiabilityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LiabilityTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LiabilityTypeId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("WealthVaultApi.Models.LiabilityTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LiabilityTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LiabilityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "home-modern",
                            IsActive = true,
                            LiabilityTypeName = "Mortgage"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "academic-cap",
                            IsActive = true,
                            LiabilityTypeName = "Student Loan"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "credit-card",
                            IsActive = true,
                            LiabilityTypeName = "Credit Card"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "car",
                            IsActive = true,
                            LiabilityTypeName = "Car Loan"
                        },
                        new
                        {
                            Id = 5,
                            IconName = "users",
                            IsActive = true,
                            LiabilityTypeName = "Personal Loan"
                        });
                });

            modelBuilder.Entity("WealthVaultApi.Models.ObligationTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ObligationTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ObligationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconName = "heart",
                            IsActive = true,
                            ObligationTypeName = "Parents Support"
                        },
                        new
                        {
                            Id = 2,
                            IconName = "book-open",
                            IsActive = true,
                            ObligationTypeName = "Kids Education"
                        },
                        new
                        {
                            Id = 3,
                            IconName = "hand-raised",
                            IsActive = true,
                            ObligationTypeName = "Charity Pledge"
                        },
                        new
                        {
                            Id = 4,
                            IconName = "plus-circle",
                            IsActive = true,
                            ObligationTypeName = "Family Medical"
                        },
                        new
                        {
                            Id = 5,
                            IconName = "plus-circle",
                            IsActive = true,
                            ObligationTypeName = "Studies"
                        },
                        new
                        {
                            Id = 6,
                            IconName = "ellipsis-h",
                            IsActive = true,
                            ObligationTypeName = "Other"
                        });
                });

            modelBuilder.Entity("WealthVaultApi.Models.Obligations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Beneficiary")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ObligationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ObligationTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ObligationTypeId");

                    b.ToTable("Obligations");
                });

            modelBuilder.Entity("WealthVaultApi.Models.Asset", b =>
                {
                    b.HasOne("WealthVaultApi.Models.AssetTypes", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("WealthVaultApi.Models.Liabilities", b =>
                {
                    b.HasOne("WealthVaultApi.Models.LiabilityTypes", "LiabilityType")
                        .WithMany("Liabilities")
                        .HasForeignKey("LiabilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiabilityType");
                });

            modelBuilder.Entity("WealthVaultApi.Models.Obligations", b =>
                {
                    b.HasOne("WealthVaultApi.Models.ObligationTypes", "ObligationType")
                        .WithMany("Obligations")
                        .HasForeignKey("ObligationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObligationType");
                });

            modelBuilder.Entity("WealthVaultApi.Models.LiabilityTypes", b =>
                {
                    b.Navigation("Liabilities");
                });

            modelBuilder.Entity("WealthVaultApi.Models.ObligationTypes", b =>
                {
                    b.Navigation("Obligations");
                });
#pragma warning restore 612, 618
        }
    }
}
