// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WealthVaultApi.Data;

#nullable disable

namespace WealthVaultApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129190006_AddedAssetTypeTable")]
    partial class AddedAssetTypeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WealthVaultApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetCurrency")
                        .HasColumnType("text");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("AssetTotalValue")
                        .HasColumnType("numeric");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("AssetYield")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("LastUpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("WealthVaultApi.Models.AssetTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DefaultYield")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiability")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("TaxAdvantaged")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
