// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WealthVaultApi.Data;

#nullable disable

namespace WealthVaultApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WealthVaultApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("YearlyYield")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chase Savings",
                            Type = "Bank",
                            Value = 75000m,
                            YearlyYield = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bitcoin",
                            PurchaseDate = new DateOnly(2025, 1, 20),
                            PurchaseValue = 12000m,
                            Qty = 1m,
                            Ticker = "bitcoin",
                            Type = "Crypto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
